language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
  - pypy

env: TOXENV=py

matrix:
  fast_finish: true
  allow_failures:
    - python: nightly
  include:
    - python: 3.6
      env: TOXENV=lint,docs
    - python: 3.6
      install: pip install -r requirements.txt
      script: ./contrib/zsh/check-all-helps

install: pip install tox

script: tox
